# Generated by Django 5.2.14 on 2026-05-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, default='hello@greengoldbioscience.com', help_text='Public contact email shown in the footer and contact page.', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, default='Kibbutz Dafna, Israel', max_length=255)),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
            ],
            options={
                'verbose_name': 'Brand & contact details',
            },
        ),
    ]
