# Generated by Django 5.2.14 on 2026-05-30 07:05

import cms.blocks
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_heading', models.CharField(default='Get started', max_length=200)),
                ('hero_intro', models.TextField(blank=True, default="Tell us who you are and what you're working on — we'll route your enquiry to the right specialist.")),
                ('manufacturer_form_title', models.CharField(default="I'm a cosmetics manufacturer", max_length=120)),
                ('manufacturer_form_intro', models.TextField(blank=True, default='Delivery systems, formulation, or a unique ingredient — tell us about your project.')),
                ('partner_form_title', models.CharField(default="I'm a raw-material manufacturer", max_length=120)),
                ('partner_form_intro', models.TextField(blank=True, default='Looking for distribution and cosmetic-market access? Share your product and target market.')),
                ('thank_you_text', models.CharField(default="Thank you — we've received your enquiry and will be in touch shortly.", max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_badge', models.CharField(blank=True, help_text="Small label above the title, e.g. 'For cosmetics manufacturers'.", max_length=80)),
                ('hero_heading', models.CharField(blank=True, max_length=200)),
                ('hero_intro', models.TextField(blank=True)),
                ('hero_cta_label', models.CharField(blank=True, max_length=60)),
                ('body', wagtail.fields.StreamField([('rich_text', 3), ('stats', 6), ('feature_grid', 10), ('process', 12), ('case_studies', 14), ('values', 16), ('ingredients', 18), ('image', 20), ('cta', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ul', 'ol']}), 3: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('body', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 5: ('wagtail.blocks.ListBlock', (cms.blocks.StatBlock,), {'min_num': 1}), 6: ('wagtail.blocks.StructBlock', [[('heading', 4), ('stats', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2'), ('3', '3')]}), 9: ('wagtail.blocks.ListBlock', (cms.blocks.FeatureBlock,), {'min_num': 1}), 10: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('intro', 7), ('columns', 8), ('features', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (cms.blocks.ProcessStepBlock,), {'min_num': 1}), 12: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('steps', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (cms.blocks.CaseStudyBlock,), {'min_num': 1}), 14: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('intro', 7), ('items', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (cms.blocks.ValueBlock,), {'min_num': 1}), 16: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('values', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (cms.blocks.IngredientCategoryBlock,), {'min_num': 1}), 18: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('intro', 7), ('categories', 17)]], {}), 19: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 20: ('wagtail.blocks.StructBlock', [[('image', 19), ('caption', 1)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 22: ('wagtail.blocks.ListBlock', (cms.blocks.CTAValue,), {'max_num': 2, 'min_num': 1}), 23: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('dark', 'Dark green'), ('light', 'Light')]}), 24: ('wagtail.blocks.StructBlock', [[('heading', 21), ('text', 7), ('buttons', 22), ('variant', 23)]], {})})),
                ('hero_cta_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
