# Generated by Django 5.2.14 on 2026-05-30 07:05

import cms.blocks
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 3), ('stats', 6), ('feature_grid', 10), ('process', 12), ('case_studies', 14), ('values', 16), ('ingredients', 18), ('image', 20), ('cta', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ul', 'ol']}), 3: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('body', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 5: ('wagtail.blocks.ListBlock', (cms.blocks.StatBlock,), {'min_num': 1}), 6: ('wagtail.blocks.StructBlock', [[('heading', 4), ('stats', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2'), ('3', '3')]}), 9: ('wagtail.blocks.ListBlock', (cms.blocks.FeatureBlock,), {'min_num': 1}), 10: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('intro', 7), ('columns', 8), ('features', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (cms.blocks.ProcessStepBlock,), {'min_num': 1}), 12: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('steps', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (cms.blocks.CaseStudyBlock,), {'min_num': 1}), 14: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('intro', 7), ('items', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (cms.blocks.ValueBlock,), {'min_num': 1}), 16: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('values', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (cms.blocks.IngredientCategoryBlock,), {'min_num': 1}), 18: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('intro', 7), ('categories', 17)]], {}), 19: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 20: ('wagtail.blocks.StructBlock', [[('image', 19), ('caption', 1)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 22: ('wagtail.blocks.ListBlock', (cms.blocks.CTAValue,), {'max_num': 2, 'min_num': 1}), 23: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('dark', 'Dark green'), ('light', 'Light')]}), 24: ('wagtail.blocks.StructBlock', [[('heading', 21), ('text', 7), ('buttons', 22), ('variant', 23)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(default='A scientific bridge between innovation and the cosmetics industry', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_intro',
            field=models.TextField(blank=True, default="We empower the world's leading cosmetics, dermo-cosmetics and personal-care manufacturers with custom delivery systems, science-based formulation, and novel raw materials — backed by data, not promises."),
        ),
        migrations.AddField(
            model_name='homepage',
            name='path_a_label',
            field=models.CharField(default='Explore delivery systems', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='path_a_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='path_a_text',
            field=models.CharField(default='Looking for custom delivery systems, formulation, or unique active ingredients.', max_length=240),
        ),
        migrations.AddField(
            model_name='homepage',
            name='path_a_title',
            field=models.CharField(default="I'm a cosmetics manufacturer", max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='path_b_label',
            field=models.CharField(default='Partner with us', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='path_b_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='path_b_text',
            field=models.CharField(default='Seeking distribution, industry contacts, and cosmetic-market access for your IP.', max_length=240),
        ),
        migrations.AddField(
            model_name='homepage',
            name='path_b_title',
            field=models.CharField(default="I'm a raw-material manufacturer", max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tagline',
            field=models.CharField(default="Bridging Science to Tomorrow's Beauty", max_length=120),
        ),
    ]
